// DOM tests use linkedom installed under .verify/ui-tests (no browser required).
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {parseHTML}=require('../.verify/ui-tests/node_modules/linkedom');
const {window}=parseHTML(fs.readFileSync('src/web/index.html','utf8'));
const document=window.document;
const ctx={clearRect(){},setTransform(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fill(){},closePath(){},fillText(){},setLineDash(){},createLinearGradient(){return {addColorStop(){}};}};
window.HTMLCanvasElement.prototype.getContext=()=>ctx;
window.Element.prototype.getBoundingClientRect=()=>({width:700,height:226,left:0,top:0});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._testValue||this.querySelector('option')?.getAttribute('value')||'';},set(v){this._testValue=v;}});
const sandbox={document,window,console,URL,Blob,AbortController,Promise,setTimeout(){return 0;},clearTimeout(){},fetch:async()=>({ok:true,status:200,text:async()=>'{}'})};
window.location={hash:''};window.devicePixelRatio=1;
const source=fs.readFileSync('src/web/app.js','utf8').replace(/\r\n/g,'\n').replace('  if (document.readyState === "loading") {','  globalThis.testing = {state, usageData, renderUsage, initUsage, showView};\n  if (false) {').replace('    init();\n  }\n})();','  }\n})();');
vm.runInNewContext(source,sandbox);
const t=sandbox.testing,today=Math.floor(Date.now()/86400000);
t.state.usage={total_in:2000,total_out:500,total_cached:300,total_requests:20,days:[{day:today,in:1000,out:300,cached:200,requests:10},{day:today-1,in:500,out:100,cached:80,requests:5}],models:[{model:'oc/muse-spark',input:1200,output:300,cached:250,requests:12,days:[{day:today,input:700,output:200,cached:100,requests:7},{day:today-1,input:500,output:100,cached:150,requests:5}]},{model:'kilo/deepseek',input:300,output:100,cached:50,requests:3,days:[{day:today,input:300,output:100,cached:50,requests:3}]}]};
t.initUsage();t.renderUsage();
assert.equal(document.querySelector('#usage-total').textContent,'1.9K');
assert.equal(t.usageData().days.length,7);
assert.equal(t.usageData().total.cached,280);
assert.equal(t.usageData().rows.length,2);
assert.equal(document.querySelectorAll('#usage-model-rows tr').length,2);
document.querySelector('[data-usage-view="models"]').click();assert.equal(document.querySelector('#usage-models').hidden,false);assert.equal(document.querySelector('#usage-timeline').hidden,true);
document.querySelector('#usage-model-rows .model-link').click();assert.equal(t.state.usageModel,'oc/muse-spark');assert.equal(document.querySelector('#usage-total').textContent,'1.5K');
let range=document.querySelector('#usage-range');range.value='1';range.dispatchEvent(new window.Event('change'));assert.equal(document.querySelector('#usage-total').textContent,'900');assert.equal(t.usageData().days.length,1);
let model=document.querySelector('#usage-model');model.value='';model.dispatchEvent(new window.Event('change'));range.value='all';range.dispatchEvent(new window.Event('change'));assert.equal(document.querySelector('#usage-total').textContent,'2.5K');assert.equal(t.usageData().rows.find(r=>r.model==='__unattributed__').input,500);
document.querySelector('[data-usage-view="days"]').click();assert.equal(document.querySelectorAll('#usage-day-rows tr').length,30);assert.equal(document.querySelector('#usage-days').hidden,false);
let blob;const original=URL.createObjectURL;URL.createObjectURL=(b)=>{blob=b;return 'blob:test';};document.querySelector('#usage-export').click();assert(blob);URL.createObjectURL=original;
t.state.usage={days:[],models:[]};t.state.usageModel='';t.renderUsage();assert.equal(document.querySelector('#usage-total').textContent,'0');assert(document.querySelector('#usage-model-rows').textContent.includes('No model usage'));
console.log('PASS usage date/model filters, tabs, drill-down, legacy attribution, zero-filled days, empty states and CSV export');
console.log('PASS no duplicate HTML ids:',new Set([...document.querySelectorAll('[id]')].map(n=>n.id)).size === document.querySelectorAll('[id]').length);
